name: Community Chess Move Handler

on:
  issue_comment:
    types: [created]

jobs:
  handle-move:
    runs-on: ubuntu-latest

    if: contains(github.event.comment.body, '/move')

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate move and check duplicate turn
        id: validation
        run: |
          COMMENT="${{ github.event.comment.body }}"
          CURRENT_USER="${{ github.event.comment.user.login }}"
          MOVE=$(echo "$COMMENT" | sed -nE 's|.*\/move\s+([^ ]+).*|\1|p')

          if [[ -z "$MOVE" ]]; then
            echo "No move found after /move. Exiting."
            echo "should_exit=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Parsed move: $MOVE"
          echo "move=$MOVE" >> $GITHUB_OUTPUT
          echo "current_user=$CURRENT_USER" >> $GITHUB_OUTPUT

          LAST_USER=$(jq -r '.last_move_by' data/data.json || echo "")

          if [[ "$CURRENT_USER" == "$LAST_USER" ]]; then
            echo "duplicate_user=true" >> $GITHUB_OUTPUT
            echo "should_exit=true" >> $GITHUB_OUTPUT
          else
            echo "duplicate_user=false" >> $GITHUB_OUTPUT
            echo "should_exit=false" >> $GITHUB_OUTPUT
          fi

      - name: Warn user for consecutive move and exit
        if: steps.validation.outputs.duplicate_user == 'true'
        run: |
          USERNAME="${{ steps.validation.outputs.current_user }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"

          echo "Posting warning to user $USERNAME on issue $ISSUE_NUMBER"

          gh api \
            -X POST \
            repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments \
            -f body="👋 Hey @${USERNAME}, you've already made the last move. Please let others take a turn before playing again! 🤝"

          echo "Duplicate move detected. Stopping workflow."
          exit 0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop workflow if move is invalid
        if: steps.validation.outputs.should_exit == 'true'
        run: |
          echo "Move was invalid or user tried to play twice. Stopping workflow."
          exit 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py with the move
        if: steps.validation.outputs.should_exit == 'false'
        run: |
          python3 main.py "${{ steps.validation.outputs.current_user }}" "${{ steps.validation.outputs.move }}"

      - name: Commit and push changes
        if: steps.validation.outputs.should_exit == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git add .
          git commit -m "♟️ `${{ steps.validation.outputs.move }}` played by: ${{ steps.validation.outputs.current_user }}"
          git push
